import 'package:flutter/material.dart';

import 'dart:async' show Future;
import 'package:flutter/services.dart' show rootBundle;
import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:multilingual_dictionary/download_database.dart';

void main() {
  runApp(const MyApp());
}

Future<List<String>> getJson() async {
  String rawJson = await rootBundle.loadString('lib/languagesKaikki.json');

  return List<String>.from(json.decode(rawJson));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: '0',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Languages'),
      ),
      body: FutureBuilder(
          future: getJson(),
          builder: (context, data) {
            if (!data.hasData) {
              return const Center(child: CircularProgressIndicator());
            }
            var items = data.data as List<String>;

            return ListView.builder(
              itemCount: items.length,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text(items[index]),
                  trailing: OutlinedButton(
                    child: const Icon(
                      Icons.download,
                      color: Colors.blue,
                      semanticLabel: 'download',
                    ),
                    onPressed: () => download(items[index]),
                  ),
                );
              },
            );
          }),
    );
  }
}

var dasta = [
  "English",
  "Spanish",
  "Latin",
  "Italian",
  "German",
  "Russian",
  "French",
  "Portuguese",
  "Finnish",
  "Latvian",
  "Chinese",
  "Arabic",
  "Catalan",
  "Polish",
  "Japanese",
  "Dutch",
  "Swedish",
  "Esperanto",
  "Romanian",
  "Mandarin",
  "Greek",
  "Norwegian Bokmål",
  "Serbo-Croatian",
  "Hungarian",
  "Translingual",
  "Norwegian Nynorsk",
  "Macedonian",
  "Czech",
  "Bulgarian",
  "Danish",
  "Middle English",
  "Korean",
  "Galician",
  "Ancient Greek",
  "Irish",
  "Vietnamese",
  "Asturian",
  "Turkish",
  "Lithuanian",
  "Icelandic",
  "Tagalog",
  "Armenian",
  "Gothic",
  "Thai",
  "Telugu",
  "Hindi",
  "Cebuano",
  "Ido",
  "Scottish Gaelic",
  "Sanskrit",
  "Ukrainian",
  "Indonesian",
  "Georgian",
  "Persian",
  "Hebrew",
  "Welsh",
  "Old English",
  "Azerbaijani",
  "Maltese",
  "Old Norse",
  "Tamil",
  "Swahili",
  "Old Armenian",
  "Estonian",
  "Norman",
  "Albanian",
  "Cantonese",
  "Kazakh",
  "Khmer",
  "Old French",
  "Manx",
  "Yiddish",
  "Pali",
  "Faroese",
  "Malayalam",
  "Luxembourgish",
  "Slovak",
  "Malay",
  "Urdu",
  "Ladin",
  "Classical Syriac",
  "Navajo",
  "Afrikaans",
  "Basque",
  "Bengali",
  "Burmese",
  "Northern Kurdish",
  "Slovene",
  "Proto-Germanic",
  "Adyghe",
  "Northern Sami",
  "Occitan",
  "Egyptian",
  "Old Irish",
  "Scots",
  "Yoruba",
  "Ottoman Turkish",
  "Mongolian",
  "Aromanian",
  "Assamese",
  "Venetian",
  "Cimbrian",
  "Bikol Central",
  "Old Church Slavonic",
  "Proto-Slavic",
  "Zulu",
  "Middle French",
  "Bashkir",
  "Classical Nahuatl",
  "Belarusian",
  "Proto-West Germanic",
  "Gujarati",
  "Lower Sorbian",
  "Westrobothnian",
  "Volapük",
  "Middle Dutch",
  "Malagasy",
  "South Levantine Arabic",
  "Interlingua",
  "West Frisian",
  "Tibetan",
  "Livonian",
  "Plautdietsch",
  "Quechua",
  "Phalura",
  "Xhosa",
  "Hawaiian",
  "Ingrian",
  "Yakut",
  "Veps",
  "Javanese",
  "Sicilian",
  "Manchu",
  "Aramaic",
  "Greenlandic",
  "Coptic",
  "Marathi",
  "Punjabi",
  "Sumerian",
  "Nepali",
  "Crimean Tatar",
  "Kyrgyz",
  "Yola",
  "Zhuang",
  "Old Saxon",
  "Lao",
  "Romansch",
  "Tocharian B",
  "Pennsylvania German",
  "Ligurian",
  "Friulian",
  "Moroccan Arabic",
  "Uzbek",
  "Old High German",
  "Moksha",
  "Hausa",
  "Breton",
  "Saterland Frisian",
  "Cornish",
  "Shan",
  "Maori",
  "Sundanese",
  "Afar",
  "Alemannic German",
  "Hiligaynon",
  "Ladino",
  "Uyghur",
  "Tajik",
  "Marshallese",
  "Tok Pisin",
  "Proto-Finnic",
  "Hunsrik",
  "Norwegian",
  "Proto-Indo-European",
  "Kashmiri",
  "Swazi",
  "Ojibwe",
  "Kannada",
  "Ternate",
  "Pashto",
  "Cherokee",
  "Maquiritari",
  "Kumyk",
  "Assyrian Neo-Aramaic",
  "Vilamovian",
  "Central Nahuatl",
  "Proto-Samic",
  "Hijazi Arabic",
  "Sardinian",
  "German Low German",
  "Kikuyu",
  "Haitian Creole",
  "Komi-Zyrian",
  "Phuthi",
  "Kabuverdianu",
  "Tatar",
  "Mapudungun",
  "Jeju",
  "Dalmatian",
  "Walloon",
  "Sranan Tongo",
  "Prakrit",
  "Romagnol",
  "Neapolitan",
  "Garo",
  "Amharic",
  "Low German",
  "Chuvash",
  "Southern Altai",
  "Tangut",
  "Lule Sami",
  "Romani",
  "Kabardian",
  "Mauritian Creole",
  "Old Swedish",
  "Papiamentu",
  "Tokelauan",
  "Laz",
  "Mon",
  "Old Spanish",
  "Okinawan",
  "Chickasaw",
  "Fula",
  "Oromo",
  "Chichewa",
  "Old Dutch",
  "Maranao",
  "Magahi",
  "Corsican",
  "Kashubian",
  "Emilian",
  "Ugaritic",
  "Akkadian",
  "Piedmontese",
  "Aragonese",
  "Chuukese",
  "Ilocano",
  "Bambara",
  "Somali",
  "Central Franconian",
  "Balinese",
  "Proto-Celtic",
  "Makasar",
  "Tuvan",
  "Silesian",
  "Karao",
  "Zazaki",
  "Chechen",
  "Turkmen",
  "Kavalan",
  "Dhivehi",
  "Middle Irish",
  "Mingrelian",
  "Karelian",
  "Middle Korean",
  "Amis",
  "Gulf Arabic",
  "Inupiaq",
  "Proto-Indo-Iranian",
  "Erzya",
  "Lushootseed",
  "West Makian",
  "Central Atlas Tamazight",
  "Central Huasteca Nahuatl",
  "Ewe",
  "Gamilaraay",
  "Old Javanese",
  "Unami",
  "Upper Sorbian",
  "Choctaw",
  "Old Georgian",
  "Proto-Brythonic",
  "Aghwan",
  "Võro",
  "Tigrinya",
  "Dupaningan Agta",
  "Wolof",
  "Urak Lawoi'",
  "Ossetian",
  "Egyptian Arabic",
  "Tausug",
  "Mohawk",
  "Ainu",
  "Old Portuguese",
  "Old Polish",
  "Oriya",
  "Waray-Waray",
  "Rwanda-Rundi",
  "Southern Ndebele",
  "Sotho",
  "Lindu",
  "Ge'ez",
  "Old Occitan",
  "Tarantino",
  "Proto-Turkic",
  "Eastern Huasteca Nahuatl",
  "Limburgish",
  "Nanai",
  "Evenki",
  "Skolt Sami",
  "Proto-Malayo-Polynesian",
  "Yogad",
  "Votic",
  "Louisiana Creole French",
  "Bourguignon",
  "Inari Sami",
  "Lingala",
  "Tetelcingo Nahuatl",
  "North Frisian",
  "Min Nan",
  "Livvi",
  "Kapampangan",
  "Sakizaya",
  "Lombard",
  "Old Frisian",
  "Taos",
  "Anguthimri",
  "Lakota",
  "Tetum",
  "Kalasha",
  "Mirandese",
  "Fijian",
  "Proto-Italic",
  "Cahuilla",
  "Baluchi",
  "Pite Sami",
  "Northern Ndebele",
  "Yucatec Maya",
  "Latgalian",
  "Abkhaz",
  "Konkani",
  "Sambali",
  "Brunei Malay",
  "Middle Armenian",
  "Old Japanese",
  "Tocharian A"
];
